const data = {
  pizzas: [
    {
      id: 1,
      name: "Farm Fresh",
      description: "Direct from the farm",
      subtitle: "99* 225+ 395^",
      price: { regular: 99, medium: 225, large: 395 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/farm-fresh.jpg",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: 2,
      name: "Cheesy Burst",
      description: "Fill the hunger of cheese",
      subtitle: "99* 225+ 395^",
      price: { regular: 129, medium: 245, large: 445 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/cheese-loaded.jpg",
      rating: 4.1,
      numReviews: 8,
    },
    {
      id: 3,
      name: "Italian",
      description: "Taste the new Italian pizza",
      subtitle: "99* 225+ 395^",
      price: { regular: 119, medium: 225, large: 415 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/italian.jpg",
      rating: 3.5,
      numReviews: 6,
    },
    {
      id: 4,
      name: "Meatior",
      description: "Best for the non-veg hungeries",
      subtitle: "99* 225+ 395^",
      price: { regular: 159, medium: 249, large: 499 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Non-Veg",
      image: "/images/meat.jpg",
      rating: 4.5,
      numReviews: 12,
    },
    {
      id: 5,
      name: "Pepperoni Meatior",
      description: "non-veg combo with pepperoni and meat",
      subtitle: "99* 225+ 395^",
      price: { regular: 169, medium: 259, large: 519 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Non-Veg",
      image: "/images/pepperoni_meat.jpg",
      rating: 4.0,
      numReviews: 8,
    },
    {
      id: 6,
      name: "Pepperoni",
      description: "Get papped with the pepperoni taste",
      subtitle: "99* 225+ 395^",
      price: { regular: 129, medium: 235, large: 425 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/pepperoni.jpg",
      rating: 3.7,
      numReviews: 14,
    },
    {
      id: 7,
      name: "Farm Fresh",
      description: "Direct from the farm",
      subtitle: "99* 225+ 395^",
      price: { regular: 99, medium: 225, large: 395 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/farm-fresh.jpg",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: 8,
      name: "Cheesy Burst",
      description: "Fill the hunger of cheese",
      subtitle: "99* 225+ 395^",
      price: { regular: 129, medium: 245, large: 445 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/cheese-loaded.jpg",
      rating: 4.1,
      numReviews: 8,
    },
    {
      id: 9,
      name: "Italian",
      description: "Taste the new Italian pizza",
      subtitle: "99* 225+ 395^",
      price: { regular: 119, medium: 225, large: 415 },
      categoryID: 6,
      categoryType: 0,
      categoryName: "Veg",
      image: "/images/italian.jpg",
      rating: 3.5,
      numReviews: 6,
    },
  ],
};

export default data;
